### ISSUE TITLE
Crashes on world load with ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by brisingraerowing** [WinDanesz/SpellBundle#2] opened 2021-12-24 22:45 UTC
[Main Log](https://gist.github.com/BrisingrAerowing/a2e8bd9caf17d91842579763a85e5e5c)

The world starts to load, then the game errors and boots you back to the multiplayer screen, even if loading a singleplayer world. It seems there's a malformed packet somewhere.

EDIT: And removing this mod allows the world to load.

**Comment by WinDanesz** [comment] 2021-12-25 15:25
This isn't the first time I see this error... unfortunately it's caused by the sheer number of spells and how EBWiz itself handles spell data syncing. It tries to synchronize data (server->clients) in a single packet, but with so many spells (from multiple addons), the packet is being broken into multiple parts or truncated, causing this error.
Key takeaway, I'll try to fix this from the EBWiz codebase by splitting up that packet into e.g. batches of 100 spells.

**Comment by brisingraerowing** [comment] 2021-12-25 15:28
Sounds good to me. Also, Merry Christmas!

**Comment by WinDanesz** [comment] 2021-12-27 10:43
Fixed in https://github.com/Electroblob77/Wizardry/pull/750

**Comment by WinDanesz** [comment] 2022-04-02 09:07
Should work fine in 4.3.6 Wizardry

**Closed as completed** 2022-04-02 09:06 UTC
Labels: wizardry-bug
